version: '2'

services:

    server:
        build: './server'
        environment: 
            - SCHEME=http
            - HOSTNAME=172.20.10.3
            - LISTEN_PORT=8888
            - DEBUG=1
        volumes:
            - ./server/files:/opt/little-doctor/files:rw
            - ./server/js/src:/opt/little-doctor/js/src:rw
            - ./server/js/tasks:/opt/little-doctor/js/tasks:rw
        ports:
            - "8888:8888"
